Requires glib-2.0.
(Old svn revision: 665)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5655,23 +5655,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for glib-2.0 >= 2.2.0" >&5
-echo $ECHO_N "checking for glib-2.0 >= 2.2.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for glib-2.0 >= 2.0.0" >&5
+echo $ECHO_N "checking for glib-2.0 >= 2.0.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "glib-2.0 >= 2.2.0" ; then
+        if $PKG_CONFIG --exists "glib-2.0 >= 2.0.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking GLIB_CFLAGS" >&5
 echo $ECHO_N "checking GLIB_CFLAGS... $ECHO_C" >&6
-            GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.2.0"`
+            GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.0.0"`
             echo "$as_me:$LINENO: result: $GLIB_CFLAGS" >&5
 echo "${ECHO_T}$GLIB_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking GLIB_LIBS" >&5
 echo $ECHO_N "checking GLIB_LIBS... $ECHO_C" >&6
-            GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.2.0"`
+            GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.0.0"`
             echo "$as_me:$LINENO: result: $GLIB_LIBS" >&5
 echo "${ECHO_T}$GLIB_LIBS" >&6
         else
@@ -5679,7 +5679,7 @@ echo "${ECHO_T}$GLIB_LIBS" >&6
             GLIB_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.2.0"`
+            GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0 >= 2.0.0"`
             echo $GLIB_PKG_ERRORS
         fi
 
@@ -5694,8 +5694,8 @@ echo "${ECHO_T}$GLIB_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (glib-2.0 >= 2.2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (glib-2.0 >= 2.2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (glib-2.0 >= 2.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (glib-2.0 >= 2.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
